### ISSUE TITLE
Drop the drawer/sliding-panel completely

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/branding-bar#22]
Currently if you click on the **About Us** link in the branding bar, there is a drawer that pushes the page down. This is a feature that's barely used and going forward will be much less relevant, as there won't be a need to promote as many Sunlight tools after the Open Federal consolidation.

For easier maintenance in the future, we should remove this drawer completely, along with the link that triggers it.

**Comment by jalbertbowden** [comment]
drawer/sliding-panel removed
